set nocompatible

" Vundle
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'

" Repos
Plugin 'flazz/vim-colorschemes'
Plugin 'Valloric/YouCompleteMe'

Plugin 'terryma/vim-multiple-cursors'
let g:multi_cursor_use_default_mapping=0
let g:multi_cursor_next_key='<C-n>'
let g:multi_cursor_prev_key='<C-p>'
let g:multi_cursor_skip_key='<C-x>'
let g:multi_cursor_quit_key='<Esc>'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
let g:airline#extensions#tabline#enabled = 1
let g:airline_theme='papercolor'
let g:airline_left_sep=''
let g:airline_right_sep=''
let g:airline_detect_paste=1
let g:airline#extensions#hunks#enabled = 0

Plugin 'scrooloose/nerdtree'
map <C-a> :NERDTreeToggle<CR>
let g:NERDTreeDirArrowExpandable = '▸'
let g:NERDTreeDirArrowCollapsible = '▾'

call vundle#end()

filetype on
filetype plugin indent on

syntax on

set ai			" Auto indent
set si			" Smart indent
let s:tabwidth=4
au Filetype * let &l:tabstop = s:tabwidth
au Filetype * let &l:shiftwidth = s:tabwidth
au Filetype * let &l:softtabstop = s:tabwidth

set incsearch		" Update terminal throughout search.
set ignorecase		" Ignore case when searching.
set hlsearch		" Highlight search results.

set lazyredraw		" Don't redraw while executing macros.
set magic		" For regex special characters.
set showmatch		" Show matching brackets.
set mat=2		" Matching bracket flash interval.

set noerrorbells
set novisualbell
set t_vb=
set tm=500

set lbr
set tw=500

set shortmess=a		" Abbreviated messages, no truncation.
set number
set ruler
set backspace=indent,eol,start
set hidden
set confirm
set ead=both
set showcmd
set clipboard+=unnamed
set textwidth=79
set noswapfile
set wildmenu
set wildmode=list
set t_Co=256

colorscheme github

map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l

set laststatus=2

let g:ycm_global_ycm_extra_conf = '~/.vim/bundle/YouCompleteMe/third_party/ycmd/cpp/ycm/.ycm_extra_conf.py'