#!/bin/bash

while IFS= read -u 9 -r dotfile; do
	name="${dotfile##*/}"
	basedir="$HOME"
	
	[[ $name =~ ^vim ]] && basedir="${basedir}/.vim"
	
	[[ ! -d $basedir ]] && {
		mkdir -p "$basedir" || exit 1
	}

	dest="${basedir}/${dotfile##*/}"
	
	if [[ ! -e $dest && -h $dest ]]; then
		rm -f "$dest"  # Remove broken symlink.
	elif [[ -e $dest && ! -h $dest ]]; then
		rm -i "$dest"  # Remove regular file.
	elif [[ -e $dest && -h $dest ]]; then
		continue
	fi

	ln -s "$dotfile" "$dest" || exit "$?"
done 9< <(find "${0%/*}" -maxdepth 1 -type f \! -name 'setup' \! -name '?git*' \
		  				 -exec readlink -f {} \; 2>/dev/null)
