#!/bin/bash

while IFS= read -r dotfile; do
	dest="${HOME}/${dotfile##*/}"
	if [[ ! -e $dest && -h $dest ]]; then
		rm -f "$dest"  # Remove broken symlink.
	elif [[ -e $dest && ! -h $dest ]]; then
		rm -i "$dest"  # Remove regular file.
	elif [[ -e $dest && -h $dest ]]; then
		continue
	fi
	ln -s "$dotfile" "$dest" || exit "$?"
done < <(find . -maxdepth 1 -type f ! -regex '^\.\/\(\.git\|setup\).*' -exec readlink -f {} \;)
