set nocompatible

filetype on
filetype plugin indent on

syntax off

set noexpandtab               " Make sure that every file uses real tabs, not spaces
set shiftround                " Round indent to multiple of 'shiftwidth'
set autoindent                " Copy indent from current line, over to the new line
let s:tabwidth=4
au Filetype * let &l:tabstop = s:tabwidth
au Filetype * let &l:shiftwidth = s:tabwidth
au Filetype * let &l:softtabstop = s:tabwidth

set shortmess=a		" Abbreviated messages, no truncation.
set number
set ruler
set backspace=indent,eol,start
set hidden
set confirm
set ead=both
set showcmd
set clipboard+=unnamed
set textwidth=120
set smartindent
set incsearch
set ignorecase
set hlsearch
set noswapfile
set wildmenu
set wildmode=list
set t_Co=256
