set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'

" Airline
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
"set laststatus=2
let g:airline#extensions#tabline#enabled = 1
let g:airline_theme='papercolor'
let g:airline_left_sep='|'
let g:airline_right_sep='|'
let g:airline_detect_paste=1
let g:airline#extensions#hunks#enabled = 0
let g:airline_mode_map = {
  \ '__' : '-',
  \ 'n'  : 'N',
  \ 'i'  : 'I',
  \ 'R'  : 'R',
  \ 'c'  : 'C',
  \ 'v'  : 'V',
  \ 'V'  : 'V',
  \ '' : 'V',
  \ 's'  : 'S',
  \ 'S'  : 'S',
  \ '' : 'S',
  \ }

" Nerdtree
Plugin 'scrooloose/nerdtree'
map <C-d> :NERDTreeToggle<CR>
let g:NERDTreeDirArrowExpandable = '<'
let g:NERDTreeDirArrowCollapsible = '>'

" Other repos
Plugin 'jmcantrell/vim-virtualenv'
Plugin 'flazz/vim-colorschemes'
Plugin 'hlissner/vim-multiedit'

call vundle#end()

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
filetype on
filetype plugin indent on
syntax on
set mouse=a

set noexpandtab               " Make sure that every file uses real tabs, not spaces
set shiftround                " Round indent to multiple of 'shiftwidth'
set autoindent                " Copy indent from current line, over to the new line
let s:tabwidth=4
au Filetype * let &l:tabstop = s:tabwidth
au Filetype * let &l:shiftwidth = s:tabwidth
au Filetype * let &l:softtabstop = s:tabwidth

set shortmess=a		" Abbreviated messages, no truncation.
set number
set ruler
set backspace=indent,eol,start
set hidden
set confirm
set ead=both
set showcmd
set clipboard+=unnamed
set textwidth=120
set smartindent
set incsearch
set ignorecase
set hlsearch
set noswapfile
set wildmenu
set wildmode=list
set t_Co=256
set background=light
colorscheme github

